### ISSUE TITLE
[Bug]: Join server located machine failed

### ISSUE THREAD

**Issue by Herobs** [gravitl/netmaker#1003]
### What happened?

As mentioned in the [troubleshooting](https://docs.netmaker.org/troubleshoot.html#server), I am joining the netmaker server located vm with a different port, but the server client node(netmaker-1) not in the peers list after join finished.

docker-compose.yml
```yml
services:
  netmaker:
    image: gravitl/netmaker:v0.12.1
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    # network_mode: host
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - default
      - gateway
    ports:
     - 51821-51828:51821-51828/udp
    volumes:
      - ./sqldata:/root/data
    environment:
      SERVER_API_CONN_STRING: netmaker-api.${NM_BASE_DOMAIN}:443
      SERVER_GRPC_CONN_STRING: netmaker-grpc.${NM_BASE_DOMAIN}:443
      GRPC_SSL: "on"
      DNS_MODE: "off"
      MASTER_KEY: ${NM_MASTER_KEY}
      # HOST_NETWORK: "on"
      PORT_FORWARD_SERVICES: mq,ssh
      MQ_HOST: mq
```

join command on host vm
```bash
./netclient join -t <token> --port 31830
```

bad peers on host vm
```bash
interface: nm-lnBxKZmM
  public key: 4iU7EV6eWVnmLQU2GAfxnDPQKJNxBqG5pbZkjpKUySU=
  private key: (hidden)
  listening port: 51829
root@vm-01:~#
```

good peers on another vm
```bash
interface: nm-lnBxKZmM
  public key: 0LQYjpXY9mHcldSNWX8hA25jiJTBr+amHxq9K5NYS3Y=
  private key: (hidden)
  listening port: 51821

peer: IzUPlSCpO7/dG2yaFgzJp9fZS3zpZHYO9TFdreYPhzM=
  endpoint: xx.xx.xx.xx:51821
  allowed ips: 172.29.255.254/32
  latest handshake: 25 seconds ago
  transfer: 51.56 KiB received, 77.21 KiB sent
  persistent keepalive: every 20 seconds
root@vm-02:~#
```

After read some code, maybe peer on the same machine be filtered by accident?

### Version

v0.12.1

### What OS are you using?

Linux

### Contributing guidelines

- [x] Yes, I did.
