### ISSUE TITLE
[Bug]: Unable to initialize iptables on host: lookup coredns: Try again 

### ISSUE THREAD

**Issue by Epod** [gravitl/netmaker#1112]
### Contact Details

epod [at] linux {dot} com

### What happened?

A fresh install with HOST mode enabled failed to launch with the following error

```
[netmaker] 2022-05-23 01:21:32 connecting to sqlite 
[netmaker] 2022-05-23 01:21:32 database successfully connected 
[netmaker] 2022-05-23 01:21:32 no OAuth provider found or not configured, continuing without OAuth 
[netmaker] 2022-05-23 01:21:32 setting iptables forward policy 
[netmaker] 2022-05-23 01:21:32 error setting iptables forward policy: exit status 4 
[netmaker] Fatal: Unable to initialize iptables on host: lookup coredns: Try again 
```

Everything works fine when not in HOST mode - but obviously only the single docker container is then part of the network. 

Here is the docker-compose file for the netmaker section

```
  netmaker:
    container_name: netmaker
    image: gravitl/netmaker:v0.14.0
    volumes:
      - /root/docker/netmaker/dnsconfig:/root/config/dnsconfig
      - /root/docker/netmaker/sqldata:/root/data
      - /root/docker/netmaker/certs:/etc/netmaker/
      - /usr/bin/wg:/usr/bin/wg
      - /run/xtables.lock:/run/xtables.lock
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    restart: always
    environment:
      SERVER_NAME: "brokernm.....net"
      SERVER_HOST: "..."
      SERVER_API_CONN_STRING: "apinm.....net:443"
      COREDNS_ADDR: "..."
      DNS_MODE: "on"
      SERVER_HTTP_HOST: "apinm.....net"
      API_PORT: "8081"
      CLIENT_MODE: "on"
      MASTER_KEY: "..."
      CORS_ALLOWED_ORIGIN: "*"
      DISPLAY_KEYS: "on"
      DATABASE: "sqlite"
      HOST_NETWORK: "on"
      VERBOSITY: "1"
      MANAGE_IPTABLES: "on"
      PORT_FORWARD_SERVICES: "dns"
```

### Version

v0.14.0

### Contributing guidelines

- [X] Yes, I did.
