### ISSUE TITLE
Documentation for gravitl/netclient use with docker-compose?

### ISSUE THREAD

**Issue by mikran** [gravitl/netmaker#1157]
Hi,

All the mentions of gravitl/netclient image seem to be related to use in kubernetes. For local development it could be nice to have docker-compose documentation as well.

I've managed to get this working, but only for linux so far, this works

```yaml
services:
  another_service_to_user_wireguard_network:
    network_mode: "service:wireguard"
  wireguard:
    container_name: 'wireguard'
    image: gravitl/netclient:latest
    environment:
      TOKEN: "<place your token here>"
    volumes:
      - ./data/netclient:/etc/netclient
    sysctls:
      - "net.ipv6.conf.all.forwarding=1"
    cap_add:
      - net_admin
      - sys_module
```

then on mac otherwise the same configuration but without "sysctls" and "cap_add" it fails with

```
wireguard                        | [netclient] 2022-05-30 07:48:36 unable to authenticate: failed to authenticate 400 Bad Request {“Code”:400,“Message”:“W1R3: MacAddress can’t be empty”}
```
