### ISSUE TITLE
[Bug]: Node needs to "repull" config after restart

### ISSUE THREAD

**Issue by ppoetz** [gravitl/netmaker#1393]
### Contact Details

patrick.poetz@voo.aero

### What happened?

Since last upgrade `v0.14.0` -> `v0.14.5` my nodes need to pull config again to rejoin the network.
I run 3 bare metal nodes which run netclient installed via `apt` to form a k8s cluster later on.
The nodes don't rejoin the network after a restart or crash which would need an extra startup script to execute `netclient pull` or manual intervention.

### Version

v0.14.5

### What OS are you using?

Linux

### Relevant log output

```shell
There's no explicit log about netclient when node is restarted. This one is just the log for the "rejoin/repull":

root@aio3:~# netclient pull
[netclient] 2022-07-17 06:13:51 No network selected. Running Pull for all networks.
[netclient] 2022-07-17 06:13:51 error remove interface nm-rke exit status 1
[netclient] 2022-07-17 06:13:51 UDP hole punching enabled for node aio3
[netclient] 2022-07-17 06:13:53 certificates/key saved
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment]
How are you installing/updating netclient.  If you are using your distro package manager, the latest packages should be enabling the netclient service so that it will start after a reboot.

**Comment by ppoetz** [comment]
I did a fresh install on the weekend, but still the same.
First uninstall netclient on all nodes and then reinstalled it with ansible playbooks:
```yaml
# ansible tasks
- hosts: nodes:rancher
  tasks:
    - name: uninstall netclient
      shell: |
        netclient uninstall
      become: yes
      register: _result
      failed_when: "_result.rc != 0 and 'netclient: not found' not in _result.stderr"
      changed_when: "'uninstalled netclient' in _result.stderr"
    - name: uninstall apt dependency
      ansible.builtin.apt:
        pkg: netclient
        state: absent
      become: yes
```
The above tasks translate to:
```shell
sudo netclient uninstall
sudo apt remove netclient
```

Then the fresh installation via ansible (excerpt):
```yaml
# netmaker installation comes first
...
- hosts: nodes:rancher
  any_errors_fatal: true
  pre_tasks:
    - name: Netclient prerequisites
      shell: |
        curl -sL 'https://apt.netmaker.org/gpg.key' | tee /etc/apt/trusted.gpg.d/netclient.asc
        curl -sL 'https://apt.netmaker.org/debian.deb.txt' | tee /etc/apt/sources.list.d/netclient.list
      become: yes 
    - name: Install packages
      apt:
        pkg:
          - netclient={{ netclient_version }} # netclient_version: 0.14.5-2
      become: yes
  tasks:
    - name: Join Network
      shell: |
        netclient join -t {{ hostvars['netmaker']['network_access_token'] }} {% if netmaker_ip|length > 0 %}--address {{ netmaker_ip }}{% endif %}
      register: join_result
      changed_when: "'ALREADY_INSTALLED' not in join_result.stdout"
      become: yes
...
# then make all nodes static via API
...
- name: Pull latest config
      shell: |
        netclient pull -n {{ hostvars['netmaker']['network']['id'] }}
      become: yes
    - name: ping all peers (including self)
      shell: |
        ping "{{ item }}" -c 1
      register: result
      retries: 5
      delay: 5
      until: result.rc == 0
      loop: "{{ nodes.json|map(attribute='address') }}"
```

After this everything works fine until a reboot is executed.
After a reboot I'd assume my peers are pingable. Even after 10 minutes nothing's happening. But with a `netclient pull` it's working instantly.

Since the wirguard network builds the base of my k8s cluster, nodes cannot recover automatically anymore. Right now though, it's more of an annoyance than an issue.
