### ISSUE TITLE
Suggestion: Auto generate client-sdk from swagger API documentation

### ISSUE THREAD

**Issue by Exchizz** [gravitl/netmaker#1741]
Hi,
I would like to configure netmaker from ansible. I imagine something like:
```
netmaker.egress_gateway:
   node_id: <node id>
   interface: eth0
   nat: true|false
   ranges:
      - a.b.c.d/x
      - a.d.e.b/y
   state: present
```

In order to create the ansible module(s), i need a python library that wraps the netmaker API. Instead of implementing this by hand, I was thinking if it was possible to use https://swagger.io/tools/swagger-codegen/ to generate the client SDK from your swager documentation and then release the python* client SDK whenever you release a new version of netmaker. This client SDK should then be pushed to https://pypi.org/.

\* if a golang SDK was created, it would open the possibility of creating a terraform provider

\Mathias
