### ISSUE TITLE
Question: Is it planned to support TCP relai nodes ?

### ISSUE THREAD

**Issue by restanrm** [gravitl/netmaker#426]
I'm trying to make a Kubernetes sidecar container pod join a Netmaker network. It join quite well the Netmaker network, but it's not able to “talk” with other nodes in the network. What seem to be the issue is the multiple NAT's that are between the clients.

The pod public IP:port cannot be joined directly from the other clients, the provider(of Kubernetes) doesn't forward traffic in the other way (external to internal). 

Tailscale provides DERP servers. Is it planned to support something to fallback on in case of failure to connect via UDPPunchHole ?

**Comment by afeiszli** [comment]
Hi @restanrm, we do have relay servers in Netmaker today, however, fallback is not automatic. We have roadmapped making fallback automatic, and this will hopefully be in place within the next couple of months

**Comment by afeiszli** [comment]
However, I am not sure if this is your problem on Kubernetes. Maybe it is, but we have set up containers many times that are able to talk to each other. More often the issue has been MTU, which tends to be much lower on Kubernetes. I would check "wg show", and if you see a handshake but cannot ping, this likely means MTU is too high. You can fix this by setting MTU to 1024 on all netmaker nodes (edit node in UI, change MTU field).

**Comment by afeiszli** [comment]
One other question is, how are you configuring the Endpoint in Kubernetes? You cannot simply run the netclient, since like you say, the "public IP" is not correct. If you are looking to communicate with the pod from outside the network, I would use a nodeport with a direct mapping (same port -> targetport), and then set the sidecar port to this (keep in mind sidecar port must also be exposed). This is how we do it when deploying netmaker with helm: https://github.com/gravitl/netmaker-helm

If you are only looking to connect with the container from other pods in Kubernetes, you would want to override the "endpoint" to be the container or service network IP. However, I am guessing this is not your use case.

**Comment by restanrm** [comment]
Thanks @afeiszli does connection to relai nodes is done through UDP as well ?

You're right maybe our setup is wrong. I've builded a netclient using the following Dockerfile:

```Dockerfile
ARG NM_VERSION=v0.8.5
FROM gravitl/builder as builder

RUN apk add --update git build-base libmnl-dev iptables

WORKDIR /root/
RUN git clone https://git.zx2c4.com/wireguard-go && \
    cd wireguard-go && \
    make && \
    make install

ENV WITH_WGQUICK=yes
RUN git clone https://git.zx2c4.com/wireguard-tools && \
    cd wireguard-tools && \
    cd src && \
    make && \
    make install

FROM gravitl/netclient:${NM_VERSION}

RUN apk add --no-cache --update bash libmnl iptables openresolv iproute2
COPY --from=builder /usr/bin/wireguard-go /usr/bin/wg* /usr/bin/
COPY scripts/userspace-entrypoint.sh ./entrypoint.sh

ENTRYPOINT ["/bin/sh", "./entrypoint.sh"]
```
Then, I ran this container as a sidecar to a prometheus container with the following specifications:

```yaml
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
        command:
        - bash
        - -c
        - |
          if [ ! -d /dev/net ]; then mkdir /dev/net; fi
          if [ ! -e /dev/net/tun ]; then  mknod /dev/net/tun c 10 200; fi
          /etc/netclient/netclient join -t $ACCESS_TOKEN --daemon off --name $NODE_NAME; 
          while true; do /etc/netclient/netclient checkin -n $NETWORK; sleep $SLEEP; d
```

After reducing MTU I haven't any better luck, the `wg show transfer` is still flat on the receiving part. You want to watch for handshakes with `tcpdump` ? (watching on the interface while `netclient checkin` does nothing)

Also, currently the server isn't in `CLIENT_MODE=on` so the server isn't in the network. I tried to connect the pod in the Kubernetes cluster to my local computer (behind NAT) and to a host from my company's cloud (behing NAT too). My computer and the company's computer can talk to themselves but not to the Kubernetes pod. It seems to me that the UDP ports of both the company's and my computer's seems accessible, only the one in the Kubernetes cluster isn't.

Another point that I didn't mention, the Kubernetes cluster that runs Netmaker isn't the same where the client runs on. 

Thank you very much for your response !!
